#include <iostream>


int main(void) {
//  try {
//    return run();
//  } catch (std::exception &e) {
    std::cerr << "test" << std::endl;
    return 1;
//  }
}
